version: '3.8'

networks:
  cache_network:
    driver: bridge
    name: smart_thing_network

services:
  db:
    container_name: db
    image: postgres:13.3
    networks:
      cache_network:
        aliases:
          - smart_thing_network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./docker/db/:/docker-entrypoint-initdb.d/
  app:
    container_name: smart-thing-cloud
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      cache_network:
        aliases:
          - smart_thing_network
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8080:8080
    environment:
      JWT_SECRET: U2oBc7qIgVgZgv3cSl370JQzZ4PWDYsA+PMlk4QxM0LGEH9s49/1CDHcm1F854Y0epVZaANWYhrKhe53QMpchdDOlH2ibGj1LP+6OoXcjBfh+yzUA0HYl53njiQsigK3+QOidGo11b1fkPdJ+lZgnCsRe2bhqsu48u5FXbPFyS7LeIYzj63qqfkBYT+Zc3vzIgdOpGpq9itUsNbwXafYSXBO3BEi6v0EbdIg5Qx
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_JPA_HIBERNATE_SHOW_SQL: false
      BROKER_HOST: rabbitmq
      BROKER_USER: ${BROKER_USER}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      REQUESTS_LIMIT: 10
  rabbitmq:
    container_name: rabbitmq
    build:
      context: ./docker/rabbitmq
      dockerfile: Dockerfile
    networks:
      cache_network:
        aliases:
          - smart_thing_network
    hostname: rabbitmq
    volumes:
      #      - ./rabbitmq:/var/lib/rabbitmq
      - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
