spring:
  datasource:
    url: jdbc:postgresql://192.168.1.27/smartthing
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:liquibase/dbchangelog.xml

logginglevel:
  ru.pobopo.smartthing.cloud: DEBUG
  org.hibernate: Error

jwt:
  token:
    secret: ${JWT_SECRET:}
    ttl: ${JWT_TOKEN_TTL:3600}
    refresh:
      ttl: ${JWT_REFRESH_TOKEN_TTL:864000}

users:
  - {login: '${ADMIN_LOGIN:}', password: '${ADMIN_PASSWORD:}', role: 'admin'}
  - {login: 'guest', password: '123', role: 'user'}

logging:
  file:
    name: ./log/cloud.log
  max-size: 20GB